import { lazy } from 'react'

export const AboutPage = lazy(() => import('./pages/AboutPage').then(m => ({ default: m.AboutPage })))
export const UsersPage = lazy(() => import('./pages/UsersPage').then(m => ({ default: m.UsersPage })))
export const ContactPage = lazy(() => import('./pages/ContactPage').then(m => ({ default: m.ContactPage })))
export const CustomersPage = lazy(() => import('./pages/CustomersPage').then(m => ({ default: m.CustomersPage })))
export const PartnersPage = lazy(() => import('./pages/PartnersPage').then(m => ({ default: m.PartnersPage })))
export const ResearchPage = lazy(() => import('./pages/ResearchPage').then(m => ({ default: m.ResearchPage })))
export const InsurersPage = lazy(() => import('./pages/InsurersPage').then(m => ({ default: m.InsurersPage })))
export const TermsPage = lazy(() => import('./pages/TermsPage').then(m => ({ default: m.TermsPage })))
export const PrivacyPage = lazy(() => import('./pages/PrivacyPage').then(m => ({ default: m.PrivacyPage })))
export const WhyBlissmiPage = lazy(() => import('./pages/WhyBlissmiPage').then(m => ({ default: m.WhyBlissmiPage })))
export const HowItWorksPage = lazy(() => import('./pages/HowItWorksPage').then(m => ({ default: m.HowItWorksPage })))
export const ClinicalTrustPage = lazy(() => import('./pages/ClinicalTrustPage').then(m => ({ default: m.ClinicalTrustPage })))
export const HowToStartPage = lazy(() => import('./pages/HowToStartPage').then(m => ({ default: m.HowToStartPage })))
export const ResourcesPage = lazy(() => import('./pages/ResourcesPage').then(m => ({ default: m.ResourcesPage })))
export const BrokersPage = lazy(() => import('./pages/BrokersPage').then(m => ({ default: m.BrokersPage })))
export const HospitalityPage = lazy(() => import('./pages/HospitalityPage').then(m => ({ default: m.HospitalityPage })))
export const SolutionsPage = lazy(() => import('./pages/SolutionsPage').then(m => ({ default: m.SolutionsPage })))
export const OutcomesPage = lazy(() => import('./pages/OutcomesPage').then(m => ({ default: m.OutcomesPage })))
export const ProofPage = lazy(() => import('./pages/ProofPage').then(m => ({ default: m.ProofPage })))
export const ExperienceLabsPage = lazy(() => import('./pages/ExperienceLabsPage').then(m => ({ default: m.ExperienceLabsPage })))
